const cardDetails = [
  {
    id: 1,
    walletName: "Rent",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 1,
    target: 2,
    cardStatus: "Acive",
    startDate: "04/09/22",
    endDate: "05/10/22",
    transactionMethod: "Manual",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 2,
    walletName: "Fees",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 6,
    target: 5,
    cardStatus: "Active",
    startDate: "05/11/22",
    endDate: "23/01/23",
    transactionMethod: "Automatic",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Failed",
  },
  {
    id: 3,
    walletName: "Car",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 5,
    target: 1,
    cardNumber: "Active",
    startDate: "01/02/22",
    endDate: "13/12/22",
    transactionMethod: "Manual",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Failed",
  },
  {
    id: 4,
    walletName: "Business",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 2,
    target: 2,
    cardStatus: "Active",
    startDate: "12/06/22",
    endDate: "09/11/23",
    transactionMethod: "Automatic",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Pending",
  },
  {
    id: 5,
    walletName: "Upkeep",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 4,
    target: 1,
    cardStatus: "Active",
    startDate: "04/06/22",
    endDate: "02/12/22",
    transactionMethod: "Manual",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 6,
    walletName: "New laptop",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 90400,
    target: 17000,
    cardStatus: "Active",
    startDate: "05/02/22",
    endDate: "02/12/23",
    transactionMethod: "Automatic",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 7,
    walletName: "Siblings",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 8000,
    target: 20000,
    cardStatus: "Active",
    startDate: "07/03/22",
    endDate: "02/12/23",
    transactionMethod: "Manual",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 8,
    walletName: "Vacation",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 40600,
    target: 1009000,
    cardStatus: "Active",
    startDate: "06/08/22",
    endDate: "02/12/23",
    transactionMethod: "Automatic",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 9,
    walletName: "New phone",
    logo: "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 5600,
    target: 10000,
    cardStatus: "Activ",
    startDate: "07/12/22",
    endDate: "02/12/23",
    transactionMethod: "Manual",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
];
export default cardDetails;
