const cardDetails = [
  {
    id: 1,
    walletName: "Rent",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 17000,
    target: 200000,
    cardStatus: "Acive",
    expirationDate: "05/10/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 2,
    walletName: "Fees",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 60000,
    target: 500000,
    cardStatus: "Active",
    expirationDate: "23/01/23",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Failed",
  },
  {
    id: 3,
    walletName: "Car",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 50000,
    target: 150000,
    cardNumber: "Active",
    expirationDate: "13/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Failed",
  },
  {
    id: 4,
    walletName: "Business",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 25000,
    target: 200000,
    cardStatus: "Active",
    expirationDate: "09/11/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Pending",
  },
  {
    id: 5,
    walletName: "Upkeep",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 40000,
    target: 100000,
    cardStatus: "Active",
    expirationDate: "02/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 6,
    walletName: "New laptop",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 90400,
    target: 17000,
    cardStatus: "Active",
    expirationDate: "02/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 7,
    walletName: "Siblings",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 8000,
    target: 20000,
    cardStatus: "Active",
    expirationDate: "02/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 8,
    walletName: "Vacation",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 40600,
    target: 1009000,
    cardStatus: "Active",
    expirationDate: "02/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
  {
    id: 9,
    walletName: "New phone",
    logo:
      "https://res.cloudinary.com/isreal/image/upload/v1663199426/banking%20app/AJIS_FILE_1_arvnbd_dqrxio.png",
    amount: 5600,
    target: 10000,
    cardStatus: "Activ",
    expirationDate: "02/12/22",
    cardHolderName: "JUSTICE AGBOMA",
    transactionStatus: "Success",
  },
];
export default cardDetails;
